// Code generated by tools/gen_builtin_methods; DO NOT EDIT.
// Source: builtin_methods.json

package main

var builtinMethods = map[string]map[string]builtinMethodInfo{
	"HashMap": {
		"clear":    {Signature: "func clear() -> (void)", Doc: "Removes all entries from the map."},
		"contains": {Signature: "func contains(key: &K) -> (bool)", Doc: "Returns true if the map contains the given key."},
		"get":      {Signature: "func get(key: &K) -> (Result<V, string>)", Doc: "Looks up a key and returns Result<V, string>."},
		"insert":   {Signature: "func insert(key: K, value: V) -> (void)", Doc: "Inserts or updates a key-value pair."},
		"isEmpty":  {Signature: "func isEmpty() -> (bool)", Doc: "Returns true if the map has no entries."},
		"keys":     {Signature: "func keys() -> (Vec<K, _>)", Doc: "Returns a vector of all keys in the map."},
		"len":      {Signature: "func len() -> (int)", Doc: "Returns the number of key-value pairs in the map."},
		"remove":   {Signature: "func remove(key: &K) -> (Result<V, string>)", Doc: "Removes and returns the value for the given key."},
		"values":   {Signature: "func values() -> (Vec<V, _>)", Doc: "Returns a vector of all values in the map."},
	},
	"Map": {
		"clear":    {Signature: "func clear() -> (void)", Doc: "Removes all entries from the map."},
		"contains": {Signature: "func contains(key: K) -> (bool)", Doc: "Returns true if the map contains the given key."},
		"keys":     {Signature: "func keys() -> (Vec<K, _>)", Doc: "Returns a vector of all keys in the map."},
		"len":      {Signature: "func len() -> (int)", Doc: "Returns the number of key-value pairs in the map."},
		"remove":   {Signature: "func remove(key: K) -> (void)", Doc: "Removes the entry with the given key."},
		"values":   {Signature: "func values() -> (Vec<V, _>)", Doc: "Returns a vector of all values in the map."},
	},
	"Result": {
		"isErr":     {Signature: "func isErr() -> (bool)", Doc: "Returns true if the result is Err."},
		"isOk":      {Signature: "func isOk() -> (bool)", Doc: "Returns true if the result is Ok."},
		"toString":  {Signature: "func toString() -> (string)", Doc: "Returns a string representation of the Result."},
		"unwrap":    {Signature: "func unwrap() -> (T)", Doc: "Returns the Ok value. Panics if Err."},
		"unwrapErr": {Signature: "func unwrapErr() -> (E)", Doc: "Returns the Err value. Panics if Ok."},
	},
	"Vec": {
		"append":   {Signature: "func append(other: Vec<T, _>) -> (void)", Doc: "Appends all elements from another vector."},
		"cap":      {Signature: "func cap() -> (int)", Doc: "Returns the vector capacity."},
		"clear":    {Signature: "func clear() -> (void)", Doc: "Removes all elements from the vector."},
		"contains": {Signature: "func contains(value: T) -> (bool)", Doc: "Returns true if the vector contains the value."},
		"first":    {Signature: "func first() -> (Result<T, string>)", Doc: "Returns the first element, or Err if empty."},
		"get":      {Signature: "func get(index: int) -> (Result<T, string>)", Doc: "Returns the element at index, or Err if out of bounds."},
		"isEmpty":  {Signature: "func isEmpty() -> (bool)", Doc: "Returns true if the vector has no elements."},
		"join":     {Signature: "func join(separator: string) -> (string)", Doc: "Concatenates elements using a separator."},
		"last":     {Signature: "func last() -> (Result<T, string>)", Doc: "Returns the last element, or Err if empty."},
		"len":      {Signature: "func len() -> (int)", Doc: "Returns the number of elements in the vector."},
		"pop":      {Signature: "func pop() -> (Result<T, string>)", Doc: "Removes and returns the last element of the vector, or Err if empty."},
		"push":     {Signature: "func push(value: T) -> (void)", Doc: "Pushes an element to the end of the vector."},
		"remove":   {Signature: "func remove(index: int) -> (Result<T, string>)", Doc: "Removes and returns the element at the given index."},
		"reverse":  {Signature: "func reverse() -> (void)", Doc: "Reverses elements in place."},
		"set":      {Signature: "func set(index: int, value: T) -> (void)", Doc: "Sets the element at index."},
		"slice":    {Signature: "func slice(start: int, end: int) -> (Vec<T, _>)", Doc: "Returns a sub-vector between start and end."},
		"toVec":    {Signature: "func toVec() -> (Vec<T, _>)", Doc: "Returns a dynamic Vec copy."},
	},
	"string": {
		"bytes":       {Signature: "func bytes() -> (Vec<int, _>)", Doc: "Returns the byte representation of the string as a vector of integers."},
		"chars":       {Signature: "func chars() -> (Vec<char, _>)", Doc: "Returns the characters of the string as a vector of chars."},
		"contains":    {Signature: "func contains(substr: string) -> (bool)", Doc: "Returns true if the string contains the substring."},
		"endsWith":    {Signature: "func endsWith(suffix: string) -> (bool)", Doc: "Returns true if the string ends with suffix."},
		"get":         {Signature: "func get(index: int) -> (Result<char, string>)", Doc: "Returns the character at index, or Err if out of bounds."},
		"hash":        {Signature: "func hash() -> (int)", Doc: "Returns the hash code of the string."},
		"indexOf":     {Signature: "func indexOf(substr: string) -> (Result<int, string>)", Doc: "Returns the index of the first occurrence of the substring, or Err if not found."},
		"lastIndexOf": {Signature: "func lastIndexOf(substr: string) -> (Result<int, string>)", Doc: "Returns the index of the last occurrence of the substring, or Err if not found."},
		"len":         {Signature: "func len() -> (int)", Doc: "Returns the length of the string in bytes."},
		"lines":       {Signature: "func lines() -> (Vec<string, _>)", Doc: "Returns the lines of the string."},
		"parseFloat":  {Signature: "func parseFloat() -> (Result<float64, string>)", Doc: "Parses the string as a float."},
		"parseInt":    {Signature: "func parseInt() -> (Result<int, string>)", Doc: "Parses the string as an integer."},
		"replace":     {Signature: "func replace(old: string, new: string) -> (string)", Doc: "Replaces all occurrences of old with new."},
		"split":       {Signature: "func split(sep: string) -> (Vec<string, _>)", Doc: "Splits the string by the given separator."},
		"startsWith":  {Signature: "func startsWith(prefix: string) -> (bool)", Doc: "Returns true if the string starts with prefix."},
		"substring":   {Signature: "func substring(start: int, end: int) -> (string)", Doc: "Returns a substring from start (inclusive) to end (exclusive)."},
		"toString":    {Signature: "func toString() -> (string)", Doc: "Returns this string value."},
		"trim":        {Signature: "func trim() -> (string)", Doc: "Returns the string with leading and trailing whitespace removed."},
	},
}

var builtinStaticMethods = map[string]map[string]builtinMethodInfo{
	"HashMap": {
		"new":     {Signature: "func new() -> (HashMap<K, V>)", Doc: "Creates an empty hash map."},
		"withCap": {Signature: "func withCap(c: int) -> (HashMap<K, V>)", Doc: "Creates an empty hash map with reserved capacity."},
	},
	"Vec": {
		"from":    {Signature: "func from<N>(arr: Vec<T, N>) -> (Vec<T, _>)", Doc: "Creates a dynamic vector from a fixed-size vector."},
		"new":     {Signature: "func new() -> (Vec<T, _>)", Doc: "Creates an empty vector."},
		"withCap": {Signature: "func withCap(cap: int) -> (Vec<T, _>)", Doc: "Creates an empty vector with reserved capacity."},
	},
}
