package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strconv"
)

type methodInfo struct {
	Signature string `json:"signature"`
	Doc       string `json:"doc"`
}

type builtinMethodsData struct {
	Instance map[string]map[string]methodInfo `json:"instance"`
	Static   map[string]map[string]methodInfo `json:"static"`
}

func main() {
	var inputPath string
	var outputPath string

	flag.StringVar(&inputPath, "in", "builtin_methods.json", "path to builtin methods JSON")
	flag.StringVar(&outputPath, "out", "builtin_methods_gen.go", "output Go file path")
	flag.Parse()

	raw, err := os.ReadFile(inputPath)
	if err != nil {
		fail("read input", err)
	}

	var data builtinMethodsData
	if err := json.Unmarshal(raw, &data); err != nil {
		fail("unmarshal JSON", err)
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by tools/gen_builtin_methods; DO NOT EDIT.\n")
	buf.WriteString("// Source: " + inputPath + "\n\n")
	buf.WriteString("package main\n\n")

	writeMethodMap(&buf, "builtinMethods", data.Instance)
	buf.WriteString("\n")
	writeMethodMap(&buf, "builtinStaticMethods", data.Static)

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fail("format generated source", err)
	}

	if err := os.WriteFile(outputPath, formatted, 0o644); err != nil {
		fail("write output", err)
	}
}

func writeMethodMap(
	buf *bytes.Buffer,
	varName string,
	byType map[string]map[string]methodInfo,
) {
	buf.WriteString("var " + varName + " = map[string]map[string]builtinMethodInfo{\n")

	typeNames := sortedKeys(byType)
	for _, typeName := range typeNames {
		methods := byType[typeName]
		buf.WriteString("\t" + strconv.Quote(typeName) + ": {\n")

		methodNames := sortedKeys(methods)
		for _, methodName := range methodNames {
			info := methods[methodName]
			buf.WriteString(
				"\t\t" + strconv.Quote(methodName) + ": {Signature: " +
					strconv.Quote(info.Signature) + ", Doc: " +
					strconv.Quote(info.Doc) + "},\n",
			)
		}
		buf.WriteString("\t},\n")
	}

	buf.WriteString("}\n")
}

func sortedKeys[T any](m map[string]T) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func fail(action string, err error) {
	_, _ = fmt.Fprintf(
		os.Stderr,
		"gen_builtin_methods: %s: %v\n",
		action,
		err,
	)
	os.Exit(1)
}
